name: Elixir Scaffold Test CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]
  workflow_run:
    workflows: ["Main release"]
    types: [completed]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Echo Branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Echo Event
        run: echo "${{ github.event_name }}"
      - name: Set up Elixir
        uses: erlef/setup-elixir@1.15.2
        with:
          elixir-version: '1.13.4' # Define the elixir version [required]
          otp-version: '24' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
      - name: Set release env
        if: github.event_name == 'release'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Upgrade mix.exs
        if: github.event_name == 'release'
        run: sed -i 's/@version \".*\"/@version "${{ env.RELEASE_VERSION }}"/g' mix.exs
      - name: Save version
        if: github.event_name == 'release'
        uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          commit-message: 'Upgrade version to ${{ env.RELEASE_VERSION }}'
          force-add: "true"
          files: mix.exs
          name: Release Bot
          email: santicalleg@hotmail.com
      - name: Publish
        if: github.event_name == 'release'
        run: echo "========== PUBLISH!!! =========="
        #run: mix hex.publish --replace --yes
        #env:
        #  HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
